version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumen-php
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini-local:/usr/local/etc/php/php.ini
    depends_on:
      - mysql

  nginx:
    image: nginx:1.17
    container_name: lumen-nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8
    container_name: lumen-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "lumen-api"
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf

volumes:
  mysql-data:
